auth:
  credentials:
  - password: '1988'
    username: ''
category: unknown
comment: 'Level: Administrator; Doc: http://www.amx.com/techsupport/PDFs/981.pdf; '
name: AMX - Environmental Controls ENV-VST-C
port: 0
vendor: AMX
